name: actions-demo-pr-test

# Controls when the action will run.
# only run on pull request action
on:
  pull_request:
    types:
      - opened
    branches:
      - main

# Run jobs sequentially or in parallel
jobs:
  test:
    name: Unit Test & Configuration
    # The type of runner that the job will run on (can be a container)
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      # Create python env
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # Install dependencies to use
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Run Tests & Coverage
        run: |
          echo Running tests...
          nosetests test/test_fail.py --with-coverage --cover-package=demo --cover-inclusive --cover-tests --cover-html --cover-html-dir=./coverage
